version: '3'
services:
  ansible-control:
    # Uncomment the next line to use a non-root user for all processes.
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: vscode

    build: 
      context: .
      dockerfile: Dockerfile
    hostname: ansible-control
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ansible-control:/app
      - ..:/app/.ansible-control
      - ${USERPROFILE}/.ssh:/root/.host/.ssh
    environment:
      - PROJECT_PATH=ansible
      - "GIT_REPO=git@github.com:ilude/ansible-control.git"
    # Overrides default command so things don't shut down after the process ends.
    #entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
    
volumes:
  ansible-control: